<?php
// Generate PHP literals safely; never interpolate environment values as code.
require __DIR__ . '/../data/config.php';
$defaults = (new ReflectionClass('config'))->getConstants();
$values = $defaults;
foreach ($defaults as $key=>$default) {
    $raw = getenv('FOURGET_'.$key);
    if ($raw === false || $key === 'VERSION') { continue; }
    if (is_array($default)) {
        $values[$key] = $raw === '' ? [] : array_map('trim', explode(',', $raw));
    } elseif (is_int($default)) {
        if (!preg_match('/\A[0-9]+\z/', $raw) || filter_var($raw,FILTER_VALIDATE_INT)===false) {
            throw new RuntimeException('Invalid integer configuration: '.$key);
        }
        $values[$key] = (int)$raw;
    } elseif (is_bool($default)) {
        $parsed = filter_var($raw,FILTER_VALIDATE_BOOLEAN,FILTER_NULL_ON_FAILURE);
        // Proxy values can also name a private pool.
        $values[$key] = $parsed === null ? $raw : $parsed;
    } else {
        $values[$key] = $raw;
    }
}
// Historical source used a string here. Normalize it to a real boolean.
$api = filter_var($values['API_ENABLED'],FILTER_VALIDATE_BOOLEAN,FILTER_NULL_ON_FAILURE);
if ($api===null) { throw new RuntimeException('Invalid boolean configuration: API_ENABLED'); }
$values['API_ENABLED']=$api;
$values['CAPTCHA_DATASET']=[];
foreach (glob(__DIR__.'/../data/captcha/*',GLOB_ONLYDIR) ?: [] as $directory) {
    $values['CAPTCHA_DATASET'][]=[basename($directory),count(glob($directory.'/*') ?: [])];
}
$output="<?php\n// Generated by docker/gen_config.php\nclass config {\n";
foreach ($values as $key=>$value) { $output.='    const '.$key.' = '.var_export($value,true).";\n"; }
$output.="}\n";
$path=__DIR__.'/../data/config.php';
if (file_put_contents($path,$output,LOCK_EX)===false) { throw new RuntimeException('Cannot write generated configuration.'); }
