<?php
 // This file was generated by docker/gen_config.php
class config {
	const VERSION = 12;
	const SERVER_NAME = "Security Search";
	const SERVER_SHORT_DESCRIPTION = "Privacy-first proxy search engine";
	const SERVER_LONG_DESCRIPTION = null;
	const DEFAULT_THEME = "SecOps";
	const DEFAULT_NSFW = "yes";
	// Default providers are configurable with FOURGET_DEFAULT_SCRAPER_WEB and
	// FOURGET_DEFAULT_SCRAPER_IMAGES. Google uses the bundled CSE-compatible
	// path so it works without a separate headful-browser renderer.
	const DEFAULT_SCRAPER_WEB = "google";
	const DEFAULT_SCRAPER_IMAGES = "google";
	const API_ENABLED = "true";
	const BOT_PROTECTION = 0;
	const CAPTCHA_DATASET = [];
	const HEADER_REGEX = "/bot|wget|curl|python-requests|scrapy|go-http-client|ruby|yahoo|spider|qwant|meta/i";
	const FILTERED_HEADER_KEYS = [];
	const DISALLOWED_SSL = [];
	const MAX_SEARCHES = 10000;
	const ALT_ADDRESSES = [];
	const INSTANCES = ["https://securityops.co"];
	const USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:155.0) Gecko/20100101 Firefox/155.0";
	const PROXY_DDG = false;
	const PROXY_YAHOO = false;
	const PROXY_YAHOO_JAPAN = false;
	const PROXY_BRAVE = false;
	const PROXY_FB = false;
	const PROXY_GOOGLE = false;
	const PROXY_GOOGLE_API = false;
	const PROXY_GOOGLE_CSE = false;
	const PROXY_MULLVAD_GOOGLE = true;
	const PROXY_MULLVAD_BRAVE = true;
	const PROXY_STARTPAGE = false;
	const PROXY_QWANT = false;
	const PROXY_BAIDU = false;
	const PROXY_COCCOC = false;
	const PROXY_GHOSTERY = false;
	const PROXY_MARGINALIA = false;
	const PROXY_MOJEEK = false;
	const PROXY_SC = false;
	const PROXY_SWISSCOWS = false;
	const PROXY_SPOTIFY = false;
	const PROXY_SOLOFIELD = false;
	const PROXY_WIBY = false;
	const PROXY_CURLIE = false;
	const PROXY_YT = false;
	const PROXY_ARCHIVEORG = false;
	const PROXY_SEPIASEARCH = false;
	const PROXY_ODYSEE = false;
	const PROXY_VIMEO = false;
	const PROXY_YEP = false;
	const PROXY_PINTEREST = false;
	const PROXY_SANKAKUCOMPLEX = false;
	const PROXY_FLICKR = false;
	const PROXY_FIVEHPX = false;
	const PROXY_VSCO = false;
	const PROXY_SEZNAM = false;
	const PROXY_NAVER = false;
	const PROXY_GREPPR = false;
	const PROXY_CROWDVIEW = false;
	const PROXY_MWMBL = false;
	const PROXY_FTM = false;
	const PROXY_IMGUR = false;
	const PROXY_CARA = false;
	const PROXY_YANDEX_W = false;
	const PROXY_YANDEX_I = false;
	const PROXY_YANDEX_V = false;
	const GOOGLE_CX_ENDPOINT = "d4e68b99b876541f0";
	const MARGINALIA_API_KEY = null;
}
?>
